config/routes.rb
Lines::Application.routes.draw do
  post '/' => 'line#move'
  get '/get_in' => 'line#get_in', as: "get_in_line"
  root to: 'line#show'
end

app/models/place.rb
class Place < ActiveRecord::Base
  scope :still_waiting, lambda {
    order("id asc").where(:reached_front => false)
  }

  # Mark a place as having reached the front.
  #
  # Returns nothing.
  def reached_front!
    update_attribute(:reached_front, true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/line_controller.rb
class LineController < ApplicationController
  before_filter :verify_api_token, :only => :destroy
  before_filter :ensure_place_in_line, :only => [:show, :get_in]
  protect_from_forgery :except => [:move]
  # skip_before_filter :verify_authenticity_token, :only => :move

  def show
    @in_front = Place.still_waiting.where(["id <= ?", @place.id]).count
    @behind = Place.still_waiting.where(["id > ?", @place.id]).count
  end

  def get_in
    if @place.reached_front?
      session.delete(:place_in_line)
    end
    redirect_to root_path
  end

  def move
    move_line
    render :nothing => true
  end

private
  def next_place_in_line
    Place.create
  end

  def ensure_place_in_line
    place_id = session[:place_in_line]
    unless place_id && @place = Place.where(id: place_id).first
      @place = next_place_in_line
      session[:place_in_line] = @place.id
    end
  end

  def move_line
    if place = Place.still_waiting.first
      place.reached_front!
    end
  end

  def verify_api_token
    token = ENV['API_TOKEN']
    unless token && params[:token] == token
      head :forbidden
      false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Get in line...
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0.0"}
  %body
    = yield

    #footer
      %a{href: "https://github.com/ryansouza/line_as_a_service"}
        %img.blacktocat{src: "/blacktocat-32.png", alt: "Fork me on Github"}

app/views/line/show.html.haml
.line
  - if @place.reached_front?
    .the_front
      %h1 YOU'VE REACHED THE FRONT!
      = link_to "get back in line", get_in_line_path
  - else
    .on_the_way You are on your way...
    .in_front
      .people= @in_front
      .message People in front of you
  .behind
    .people= @behind
    .message People behind you